version: 2

project_name: runemarket

builds:
  - id: runemarket
    main: ./cmd/runemarket
    binary: runemarket
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: runemarket
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^style:'
      - '^build:'
      - Merge pull request
      - Merge branch

dockers:
  - id: runemarket-amd64
    image_templates:
      - "ghcr.io/ravenmk2/rune-market:{{ .Version }}-amd64"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: runemarket-arm64
    image_templates:
      - "ghcr.io/ravenmk2/rune-market:{{ .Version }}-arm64"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/ravenmk2/rune-market:{{ .Version }}"
    image_templates:
      - "ghcr.io/ravenmk2/rune-market:{{ .Version }}-amd64"
      - "ghcr.io/ravenmk2/rune-market:{{ .Version }}-arm64"
  - name_template: "ghcr.io/ravenmk2/rune-market:latest"
    image_templates:
      - "ghcr.io/ravenmk2/rune-market:{{ .Version }}-amd64"
      - "ghcr.io/ravenmk2/rune-market:{{ .Version }}-arm64"
